package jmri.jmrix.loconet;

import org.netbeans.junit.NbTestCase;

/**
 * Generated by JBuilder
 * <p>
 * Title: LnPacketizerTest </p>
 * <p>
 * Description: </p>
 * <p>
 * Copyright: Copyright (c) 2002</p>
 *
 * @author Bob Jacobsen
 * @version $Id$
 */
public class LnPacketizerTest extends NbTestCase {

    public LnPacketizerTest(String s) {
        super(s);
    }

    public void testDummy() {
    }

    // The minimal setup for log4J
    protected void setUp() {
        apps.tests.Log4JFixture.setUp();
    }

    protected void tearDown() {
        apps.tests.Log4JFixture.tearDown();
    }
}
