/*============================================================================*
 * WARNING      This class contains automatically modified code.      WARNING *
 *                                                                            *
 * The method initComponents() and the variable declarations between the      *
 * "// Variables declaration - do not modify" and                             *
 * "// End of variables declaration" comments will be overwritten if modified *
 * by hand. Using the NetBeans IDE to edit this file is strongly recommended. *
 *                                                                            *
 * See http://jmri.org/help/en/html/doc/Technical/NetBeansGUIEditor.shtml for *
 * more information.                                                          *
 *============================================================================*/
package org.jmri.roster.ui;

import java.io.Serializable;
import javax.swing.Action;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
import javax.swing.JToolBar;
import jmri.jmrit.roster.RosterEntry;
import jmri.jmrit.roster.RosterEntryPane;
import jmri.jmrit.roster.swing.RosterEntryNetBeansGlue;
import org.jmri.roster.RosterEntryProxy;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.openide.awt.UndoRedo;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Randall Wood <randall.h.wood@alexandriasoftware.com>
 */
@MultiViewElement.Registration(
        displayName = "#LBL_RosterEntryPanel",
        mimeType = "application/x-jmri-rosterentry-node",
        iconBase = "org/jmri/roster/ui/RosterEntry.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER,
        preferredID = "RosterEntry",
        position = 10)
@NbBundle.Messages("LBL_RosterEntryPanel=Roster Entry")
//@ConvertAsProperties(dtd = "-//org.jmri.roster.ui//RosterEntryMediaPanel//EN", autostore = false)
public class RosterEntryPanel extends TopComponent implements MultiViewElement, RosterEntryNetBeansGlue, Serializable {

    private static final Logger log = LoggerFactory.getLogger(RosterEntryPanel.class);
    private static final long serialVersionUID = 4717675265389667002L;
    private final RosterEntry rosterEntry;
    private final InstanceContent instanceContent;
    private final Lookup lookup;

    /**
     * Creates new form RosterEntryPanel
     */
    public RosterEntryPanel(Lookup lookup) {
        this.lookup = lookup;
        this.rosterEntry = lookup.lookup(RosterEntryProxy.class);
        this.instanceContent = lookup.lookup(InstanceContent.class);
        if (this.rosterEntry == null) {
            log.error("RosterEntry is null.");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rosterEntryPane = new RosterEntryPane(this.rosterEntry, this);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(rosterEntryPane, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(rosterEntryPane, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RosterEntryPane rosterEntryPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComponent getVisualRepresentation() {
        return this;
    }

    @Override
    public JComponent getToolbarRepresentation() {
        JToolBar toolbar = new JToolBar();
        toolbar.setFloatable(false);
        return toolbar;
    }

    @Override
    public Action[] getActions() {
        return new Action[0];
    }

    @Override
    public Lookup getLookup() {
        return this.lookup;
    }

    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    @Override
    public void componentShowing() {
    }

    @Override
    public void componentHidden() {
    }

    @Override
    public void componentActivated() {
    }

    @Override
    public void componentDeactivated() {
    }

    @Override
    public UndoRedo getUndoRedo() {
        return UndoRedo.NONE;
    }

    @Override
    public void setMultiViewCallback(MultiViewElementCallback mvec) {
        if (this.rosterEntryPane.guiChanged(this.rosterEntry)) {
            mvec.getTopComponent().setHtmlDisplayName("<html><b>" + this.rosterEntry.getDisplayName() + "</b></html>");
        } else {
            mvec.getTopComponent().setHtmlDisplayName("<html>" + this.rosterEntry.getDisplayName() + "</html>");
        }
    }

    @Override
    public CloseOperationState canCloseElement() {
        return CloseOperationState.STATE_OK;
    }

    @Override
    public void savable() {
        if (this.getLookup().lookup(RosterEntrySavable.class) == null) {
            this.instanceContent.add(new RosterEntrySavable(this.rosterEntry, this.instanceContent));
        }
    }
}
