/*============================================================================*
 * WARNING      This class contains automatically modified code.      WARNING *
 *                                                                            *
 * The method initComponents() and the variable declarations between the      *
 * "// Variables declaration - do not modify" and                             *
 * "// End of variables declaration" comments will be overwritten if modified *
 * by hand. Using the NetBeans IDE to edit this file is strongly recommended. *
 *                                                                            *
 * See http://jmri.org/help/en/html/doc/Technical/NetBeansGUIEditor.shtml for *
 * more information.                                                          *
 *============================================================================*/
package org.jmri.roster.ui;

import java.io.Serializable;
import javax.swing.Action;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JToolBar;
import jmri.jmrit.roster.RosterEntry;
import jmri.jmrit.roster.RosterMediaPane;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.openide.awt.UndoRedo;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Randall Wood <randall.h.wood@alexandriasoftware.com>
 */
@MultiViewElement.Registration(
        displayName = "#LBL_RosterEntryMediaPanel",
        mimeType = "application/x-jmri-rosterentry-node",
        persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED,
        preferredID = "RosterEntryMedia",
        position = 10)
@Messages("LBL_RosterEntryMediaPanel=Media")
public class RosterEntryMediaPanel extends JPanel implements MultiViewElement, Serializable {

    private static final Logger log = LoggerFactory.getLogger(RosterEntryMediaPanel.class);
    
    RosterEntry rosterEntry;
    /**
     * Creates new form RosterEntryMediaPanel
     */
    public RosterEntryMediaPanel(Lookup lookup) {
        this.rosterEntry = lookup.lookup(RosterEntry.class);
        if (this.rosterEntry == null) {
            log.error("RosterEntry is null.");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rosterMediaPane = new RosterMediaPane(this.rosterEntry);

        GroupLayout rosterMediaPaneLayout = new GroupLayout(rosterMediaPane);
        rosterMediaPane.setLayout(rosterMediaPaneLayout);
        rosterMediaPaneLayout.setHorizontalGroup(rosterMediaPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        rosterMediaPaneLayout.setVerticalGroup(rosterMediaPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(rosterMediaPane, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(rosterMediaPane, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private transient JPanel rosterMediaPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComponent getVisualRepresentation() {
        return this;
    }

    @Override
    public JComponent getToolbarRepresentation() {
        JToolBar toolbar = new JToolBar();
        toolbar.setFloatable(false);
        return toolbar;
    }

    @Override
    public Action[] getActions() {
        return new Action[0];
    }

    @Override
    public Lookup getLookup() {
        return Lookups.singleton(this.rosterEntry);
    }

    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    @Override
    public void componentShowing() {
    }

    @Override
    public void componentHidden() {
    }

    @Override
    public void componentActivated() {
    }

    @Override
    public void componentDeactivated() {
    }

    @Override
    public UndoRedo getUndoRedo() {
        return UndoRedo.NONE;
    }

    @Override
    public void setMultiViewCallback(MultiViewElementCallback mvec) {
        mvec.getTopComponent().setDisplayName(this.rosterEntry.getDisplayName());
    }

    @Override
    public CloseOperationState canCloseElement() {
        return CloseOperationState.STATE_OK;
    }
}
